[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.zksync]
src = 'contracts'
solc-version = "0.8.24"
fallback_oz = true
is_system = false
mode = "3"
test = 'test'
script = 'script'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']
